USE weightogo_db;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE assessments;
TRUNCATE TABLE children;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO children (name, barangay, purok, parent_name, age_months, gender, birthdate, wfa_status, hfa_status, wfhl_status, classification, weight, height, checkup_status) VALUES

-- Brgy. Caloocan (15)
('Marian Cagas',         'Brgy. Caloocan',    'Purok 1', 'Ronaldo Cagas',         3,  'Male',   '2026-04-15', 'Normal',        'Normal',        'Normal',        'normal',   5.5,  56.0, 'Pending'),
('Jolo Reyes',           'Brgy. Caloocan',    'Purok 2', 'Marites Reyes',         8,  'Male',   '2025-11-20', 'Normal',        'Normal',        'Normal',        'normal',   7.2,  65.0, 'Pending'),
('Angel Torres',         'Brgy. Caloocan',    'Purok 3', 'Renato Torres',        14,  'Female', '2025-05-10', 'Normal',        'Normal',        'Normal',        'normal',   9.1,  74.0, 'Pending'),
('Bhea Santos',          'Brgy. Caloocan',    'Purok 4', 'Joel Santos',          19,  'Female', '2024-12-05', 'Underweight',   'Normal',        'Normal',        'normal',   9.5,  78.0, 'Pending'),
('Kyle Dela Cruz',       'Brgy. Caloocan',    'Purok 1', 'Ricardo Dela Cruz',    22,  'Male',   '2024-09-15', 'Normal',        'Stunted',       'Normal',        'stunted',  9.8,  78.5, 'Pending'),
('Chloe Reyes',          'Brgy. Caloocan',    'Purok 2', 'Dennis Reyes',         28,  'Female', '2024-03-20', 'Normal',        'Normal',        'Normal',        'normal',  11.5,  86.0, 'Checked Up'),
('Ethan Cruz',           'Brgy. Caloocan',    'Purok 3', 'Lorna Cruz',           33,  'Male',   '2023-10-10', 'Normal',        'Normal',        'Normal',        'normal',  12.2,  90.0, 'Pending'),
('Alyssa Bautista',      'Brgy. Caloocan',    'Purok 4', 'Gregorio Bautista',    36,  'Female', '2023-07-01', 'Normal',        'Normal',        'Normal',        'normal',  12.5,  92.0, 'Pending'),
('Gabriel Mendoza',      'Brgy. Caloocan',    'Purok 1', 'Cristina Mendoza',     40,  'Male',   '2023-03-15', 'Overweight',    'Normal',        'Overweight',    'obese',   16.0,  96.0, 'Pending'),
('Patricia Garcia',      'Brgy. Caloocan',    'Purok 2', 'Fernando Garcia',      44,  'Female', '2022-11-20', 'Normal',        'Normal',        'Normal',        'normal',  14.5, 100.0, 'Checked Up'),
('Marco Villanueva',     'Brgy. Caloocan',    'Purok 3', 'Gloria Villanueva',    48,  'Male',   '2022-07-15', 'Normal',        'Stunted',       'Normal',        'stunted', 13.5,  95.0, 'Pending'),
('Nicole Delos Santos',  'Brgy. Caloocan',    'Purok 4', 'Arturo Delos Santos',  52,  'Female', '2022-03-10', 'Severe Underweight', 'Severe Stunted', 'Severely Wasted', 'stunted', 12.0,  90.0, 'Pending'),
('RJ Fernando',          'Brgy. Caloocan',    'Purok 1', 'Jose Fernando',        56,  'Male',   '2022-01-05', 'Normal',        'Normal',        'Overweight',    'obese',   20.0, 108.0, 'Pending'),
('Trina Bacani',         'Brgy. Caloocan',    'Purok 2', 'Susan Bacani',         58,  'Female', '2022-01-10', 'Overweight',    'Normal',        'Obese',         'obese',   22.0, 110.0, 'Checked Up'),
('Mark Lim',             'Brgy. Caloocan',    'Purok 3', 'Henry Lim',            60,  'Male',   '2021-07-15', 'Normal',        'Normal',        'Normal',        'normal',  18.0, 112.0, 'Pending'),

-- Brgy. Lanatan (15)
('Diana Pagaduan',       'Brgy. Lanatan',     'Purok 1', 'Edgar Pagaduan',        2,  'Female', '2026-05-10', 'Normal',        'Normal',        'Normal',        'normal',   4.2,  51.0, 'Pending'),
('Sean Bautista',        'Brgy. Lanatan',     'Purok 2', 'Gemma Bautista',        6,  'Male',   '2026-01-05', 'Normal',        'Normal',        'Normal',        'normal',   6.5,  62.0, 'Pending'),
('Chloe Mendoza',        'Brgy. Lanatan',     'Purok 3', 'Arturo Mendoza',       11,  'Female', '2025-08-20', 'Normal',        'Normal',        'Normal',        'normal',   8.5,  70.0, 'Pending'),
('Dan Rivera',           'Brgy. Lanatan',     'Purok 4', 'Lorna Rivera',         16,  'Male',   '2025-03-10', 'Underweight',   'Normal',        'Normal',        'normal',   9.0,  75.0, 'Pending'),
('Ella Garcia',          'Brgy. Lanatan',     'Purok 1', 'Fernando Garcia',      20,  'Female', '2024-11-15', 'Normal',        'Normal',        'Normal',        'normal',  10.0,  79.0, 'Pending'),
('Josh Orbeta',          'Brgy. Lanatan',     'Purok 2', 'Roberto Orbeta',       25,  'Male',   '2024-06-18', 'Normal',        'Stunted',       'Normal',        'stunted', 10.2,  80.0, 'Pending'),
('Mia Salazar',          'Brgy. Lanatan',     'Purok 3', 'Antonio Salazar',      30,  'Female', '2024-01-20', 'Normal',        'Normal',        'Normal',        'normal',  11.5,  87.0, 'Checked Up'),
('Carlos Ramos',         'Brgy. Lanatan',     'Purok 4', 'Pilar Ramos',          35,  'Male',   '2023-08-05', 'Normal',        'Normal',        'Normal',        'normal',  12.5,  91.0, 'Pending'),
('Hannah Flores',        'Brgy. Lanatan',     'Purok 1', 'Jun Flores',           40,  'Female', '2023-03-12', 'Normal',        'Normal',        'Normal',        'normal',  13.5,  95.0, 'Pending'),
('Aaron Velasco',        'Brgy. Lanatan',     'Purok 2', 'Rosalinda Velasco',    45,  'Male',   '2022-10-08', 'Severe Underweight', 'Severe Stunted', 'Severely Wasted', 'stunted', 12.0,  88.0, 'Pending'),
('Sara Domingo',         'Brgy. Lanatan',     'Purok 3', 'Leonardo Domingo',     50,  'Female', '2022-05-14', 'Normal',        'Normal',        'Normal',        'normal',  16.0, 105.0, 'Checked Up'),
('Miguel Hernandez',     'Brgy. Lanatan',     'Purok 4', 'Patricia Hernandez',   54,  'Male',   '2022-01-25', 'Overweight',    'Normal',        'Overweight',    'obese',   20.0, 108.0, 'Pending'),
('Cheska Panganiban',    'Brgy. Lanatan',     'Purok 1', 'Reynaldo Panganiban',  56,  'Female', '2022-01-10', 'Normal',        'Stunted',       'Normal',        'stunted', 15.0, 100.0, 'Pending'),
('Benedict Sy',          'Brgy. Lanatan',     'Purok 2', 'Helen Sy',             58,  'Male',   '2022-01-15', 'Normal',        'Normal',        'Normal',        'normal',  18.5, 112.0, 'Pending'),
('Althea Ong',           'Brgy. Lanatan',     'Purok 3', 'George Ong',           60,  'Female', '2021-07-01', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up'),

-- Brgy. Uno (15)
('RJ Fernando',          'Brgy. Uno',         'Purok 1', 'Jose Fernando',         1,  'Male',   '2026-06-10', 'Normal',        'Normal',        'Normal',        'normal',   3.8,  50.0, 'Pending'),
('Trina Bacani',         'Brgy. Uno',         'Purok 2', 'Susan Bacani',          5,  'Female', '2026-02-20', 'Normal',        'Normal',        'Normal',        'normal',   6.0,  60.0, 'Pending'),
('Mark Lim',             'Brgy. Uno',         'Purok 3', 'Henry Lim',             9,  'Male',   '2025-10-15', 'Normal',        'Normal',        'Normal',        'normal',   7.8,  68.0, 'Pending'),
('Precious Adlawan',     'Brgy. Uno',         'Purok 4', 'Victor Adlawan',       13,  'Female', '2025-06-01', 'Underweight',   'Normal',        'Normal',        'normal',   8.8,  72.0, 'Pending'),
('Bryan Soriano',        'Brgy. Uno',         'Purok 1', 'Wilfredo Soriano',     18,  'Male',   '2025-01-20', 'Normal',        'Normal',        'Normal',        'normal',  10.0,  78.0, 'Pending'),
('Angel Torres',         'Brgy. Uno',         'Purok 2', 'Renato Torres',        23,  'Female', '2024-08-10', 'Normal',        'Stunted',       'Normal',        'stunted', 10.2,  80.0, 'Pending'),
('Kyle Dela Cruz',       'Brgy. Uno',         'Purok 3', 'Ricardo Dela Cruz',    28,  'Male',   '2024-03-05', 'Normal',        'Normal',        'Normal',        'normal',  11.5,  86.0, 'Checked Up'),
('Iris Delos Santos',    'Brgy. Uno',         'Purok 4', 'Melinda Delos Santos', 33,  'Female', '2023-10-18', 'Normal',        'Normal',        'Normal',        'normal',  12.5,  90.0, 'Pending'),
('Dominic Cheng',        'Brgy. Uno',         'Purok 1', 'Teresa Cheng',         38,  'Male',   '2023-05-12', 'Normal',        'Normal',        'Normal',        'normal',  13.5,  94.0, 'Pending'),
('Frances Lee',          'Brgy. Uno',         'Purok 2', 'Antonio Lee',          43,  'Female', '2022-12-08', 'Severe Underweight', 'Severe Stunted', 'Severely Wasted', 'stunted', 12.0,  88.0, 'Pending'),
('Zach Arellano',        'Brgy. Uno',         'Purok 3', 'Boy Arellano',         48,  'Male',   '2022-07-15', 'Normal',        'Normal',        'Overweight',    'obese',   18.0, 103.0, 'Pending'),
('Gela Magsaysay',       'Brgy. Uno',         'Purok 4', 'Nena Magsaysay',       52,  'Female', '2022-03-20', 'Normal',        'Normal',        'Normal',        'normal',  16.5, 106.0, 'Checked Up'),
('TJ Rosales',           'Brgy. Uno',         'Purok 1', 'Cesar Rosales',        55,  'Male',   '2022-01-10', 'Overweight',    'Normal',        'Obese',         'obese',   21.0, 109.0, 'Pending'),
('Princess Dizon',       'Brgy. Uno',         'Purok 2', 'Armando Dizon',        57,  'Female', '2022-01-05', 'Normal',        'Stunted',       'Normal',        'stunted', 15.5, 102.0, 'Pending'),
('Nathan Belen',         'Brgy. Uno',         'Purok 3', 'Salome Belen',         60,  'Male',   '2021-07-15', 'Normal',        'Normal',        'Normal',        'normal',  18.5, 113.0, 'Checked Up'),

-- Brgy. Ermita (15)
('Zia Navarro',          'Brgy. Ermita',      'Purok 1', 'Romeo Navarro',         2,  'Female', '2026-05-25', 'Normal',        'Normal',        'Normal',        'normal',   4.5,  53.0, 'Pending'),
('Liam Bernardo',        'Brgy. Ermita',      'Purok 2', 'Carlo Bernardo',        7,  'Male',   '2025-12-10', 'Normal',        'Normal',        'Normal',        'normal',   7.0,  64.0, 'Pending'),
('Jasmine Pelayo',       'Brgy. Ermita',      'Purok 3', 'Liza Pelayo',          12,  'Female', '2025-07-20', 'Normal',        'Normal',        'Normal',        'normal',   8.9,  72.0, 'Pending'),
('Ethan Montes',         'Brgy. Ermita',      'Purok 4', 'Arnold Montes',        17,  'Male',   '2025-02-05', 'Underweight',   'Normal',        'Normal',        'normal',   9.2,  76.0, 'Pending'),
('Samantha Cruz',        'Brgy. Ermita',      'Purok 1', 'Dennis Cruz',          22,  'Female', '2024-09-15', 'Normal',        'Stunted',       'Normal',        'stunted',  9.8,  78.5, 'Pending'),
('Noel Aquino',          'Brgy. Ermita',      'Purok 2', 'Nancy Aquino',         27,  'Male',   '2024-04-08', 'Normal',        'Normal',        'Normal',        'normal',  11.2,  85.0, 'Pending'),
('Ryle Guzman',          'Brgy. Ermita',      'Purok 3', 'Alvin Guzman',         32,  'Male',   '2023-11-20', 'Normal',        'Normal',        'Normal',        'normal',  12.0,  89.0, 'Checked Up'),
('Mika Sevilla',         'Brgy. Ermita',      'Purok 4', 'Merle Sevilla',        37,  'Female', '2023-06-05', 'Normal',        'Normal',        'Normal',        'normal',  13.0,  93.0, 'Pending'),
('Ace Villarosa',        'Brgy. Ermita',      'Purok 1', 'Elena Villarosa',      42,  'Male',   '2023-01-15', 'Normal',        'Normal',        'Normal',        'normal',  14.0,  97.0, 'Pending'),
('Stella Magno',         'Brgy. Ermita',      'Purok 2', 'Virgilio Magno',       47,  'Female', '2022-08-25', 'Severe Underweight', 'Stunted', 'Severely Wasted', 'stunted', 12.5,  90.0, 'Pending'),
('Harold Natividad',     'Brgy. Ermita',      'Purok 3', 'Lourdes Natividad',    52,  'Male',   '2022-03-10', 'Normal',        'Normal',        'Overweight',    'obese',   19.0, 105.0, 'Pending'),
('Brianna Salcedo',      'Brgy. Ermita',      'Purok 4', 'Allan Salcedo',        55,  'Female', '2022-01-08', 'Normal',        'Normal',        'Normal',        'normal',  17.0, 108.0, 'Checked Up'),
('Iñigo Magtibay',       'Brgy. Ermita',      'Purok 1', 'Susan Magtibay',       57,  'Male',   '2022-01-02', 'Overweight',    'Normal',        'Obese',         'obese',   22.0, 110.0, 'Pending'),
('Rina Concepcion',      'Brgy. Ermita',      'Purok 2', 'Ramon Concepcion',     59,  'Female', '2021-08-10', 'Normal',        'Normal',        'Normal',        'normal',  18.0, 112.0, 'Pending'),
('Diego Alejo',          'Brgy. Ermita',      'Purok 3', 'Lina Alejo',           60,  'Male',   '2021-07-01', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up'),

-- Brgy. Gumamela (15)
('Liam Bernardo',        'Brgy. Gumamela',    'Purok 1', 'Carlo Bernardo',        1,  'Male',   '2026-06-15', 'Normal',        'Normal',        'Normal',        'normal',   3.5,  49.0, 'Pending'),
('Jasmine Pelayo',       'Brgy. Gumamela',    'Purok 2', 'Liza Pelayo',           4,  'Female', '2026-03-20', 'Normal',        'Normal',        'Normal',        'normal',   5.8,  58.0, 'Pending'),
('Ethan Montes',         'Brgy. Gumamela',    'Purok 3', 'Arnold Montes',         8,  'Male',   '2025-11-10', 'Normal',        'Normal',        'Normal',        'normal',   7.5,  66.0, 'Pending'),
('Samantha Cruz',        'Brgy. Gumamela',    'Purok 4', 'Dennis Cruz',          13,  'Female', '2025-06-05', 'Normal',        'Normal',        'Normal',        'normal',   9.0,  73.0, 'Pending'),
('Noel Aquino',          'Brgy. Gumamela',    'Purok 1', 'Nancy Aquino',         18,  'Male',   '2025-01-15', 'Underweight',   'Normal',        'Normal',        'normal',   9.5,  77.0, 'Pending'),
('Ryle Guzman',          'Brgy. Gumamela',    'Purok 2', 'Alvin Guzman',         23,  'Male',   '2024-08-08', 'Normal',        'Stunted',       'Normal',        'stunted', 10.0,  80.0, 'Pending'),
('Mika Sevilla',         'Brgy. Gumamela',    'Purok 3', 'Merle Sevilla',        28,  'Female', '2024-03-20', 'Normal',        'Normal',        'Normal',        'normal',  11.5,  86.0, 'Checked Up'),
('Ace Villarosa',        'Brgy. Gumamela',    'Purok 4', 'Elena Villarosa',      33,  'Male',   '2023-10-10', 'Normal',        'Normal',        'Normal',        'normal',  12.5,  90.0, 'Pending'),
('Stella Magno',         'Brgy. Gumamela',    'Purok 1', 'Virgilio Magno',       38,  'Female', '2023-05-15', 'Normal',        'Normal',        'Normal',        'normal',  13.2,  93.0, 'Pending'),
('Harold Natividad',     'Brgy. Gumamela',    'Purok 2', 'Lourdes Natividad',    43,  'Male',   '2022-12-20', 'Severe Underweight', 'Severe Stunted', 'Severely Wasted', 'stunted', 11.5,  87.0, 'Pending'),
('Brianna Salcedo',      'Brgy. Gumamela',    'Purok 3', 'Allan Salcedo',        48,  'Female', '2022-07-05', 'Normal',        'Normal',        'Normal',        'normal',  15.5, 102.0, 'Pending'),
('Iñigo Magtibay',       'Brgy. Gumamela',    'Purok 4', 'Susan Magtibay',       52,  'Male',   '2022-03-18', 'Overweight',    'Normal',        'Overweight',    'obese',   19.5, 106.0, 'Checked Up'),
('Rina Concepcion',      'Brgy. Gumamela',    'Purok 1', 'Ramon Concepcion',     55,  'Female', '2022-01-10', 'Normal',        'Normal',        'Normal',        'normal',  17.0, 108.0, 'Pending'),
('Diego Alejo',          'Brgy. Gumamela',    'Purok 2', 'Lina Alejo',           57,  'Male',   '2022-01-05', 'Normal',        'Stunted',       'Normal',        'stunted', 15.0, 100.0, 'Pending'),
('Czarina Bello',        'Brgy. Gumamela',    'Purok 3', 'Fidel Bello',          60,  'Female', '2021-07-15', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up'),

-- Brgy. Navotas (15)
('Ryle Guzman',          'Brgy. Navotas',     'Purok 1', 'Alvin Guzman',          3,  'Male',   '2026-04-10', 'Normal',        'Normal',        'Normal',        'normal',   5.2,  55.0, 'Pending'),
('Iris Delos Santos',    'Brgy. Navotas',     'Purok 2', 'Melinda Delos Santos',  7,  'Female', '2025-12-18', 'Normal',        'Normal',        'Normal',        'normal',   7.0,  64.0, 'Pending'),
('Josh Orbeta',          'Brgy. Navotas',     'Purok 3', 'Roberto Orbeta',       12,  'Male',   '2025-07-05', 'Normal',        'Normal',        'Normal',        'normal',   8.8,  72.0, 'Pending'),
('Mia Salazar',          'Brgy. Navotas',     'Purok 4', 'Antonio Salazar',      17,  'Female', '2025-02-10', 'Underweight',   'Normal',        'Normal',        'normal',   9.0,  75.0, 'Pending'),
('Carlos Ramos',         'Brgy. Navotas',     'Purok 1', 'Pilar Ramos',          22,  'Male',   '2024-09-20', 'Normal',        'Stunted',       'Normal',        'stunted',  9.8,  78.5, 'Pending'),
('Hannah Flores',        'Brgy. Navotas',     'Purok 2', 'Jun Flores',           27,  'Female', '2024-04-08', 'Normal',        'Normal',        'Normal',        'normal',  11.2,  85.0, 'Pending'),
('Aaron Velasco',        'Brgy. Navotas',     'Purok 3', 'Rosalinda Velasco',    32,  'Male',   '2023-11-15', 'Normal',        'Normal',        'Normal',        'normal',  12.0,  89.0, 'Checked Up'),
('Sara Domingo',         'Brgy. Navotas',     'Purok 4', 'Leonardo Domingo',     37,  'Female', '2023-06-01', 'Normal',        'Normal',        'Normal',        'normal',  13.0,  93.0, 'Pending'),
('Miguel Hernandez',     'Brgy. Navotas',     'Purok 1', 'Patricia Hernandez',   42,  'Male',   '2023-01-20', 'Normal',        'Normal',        'Normal',        'normal',  14.0,  97.0, 'Pending'),
('Cheska Panganiban',    'Brgy. Navotas',     'Purok 2', 'Reynaldo Panganiban',  47,  'Female', '2022-08-10', 'Severe Underweight', 'Stunted', 'Severely Wasted', 'stunted', 12.0,  88.0, 'Pending'),
('Benedict Sy',          'Brgy. Navotas',     'Purok 3', 'Helen Sy',             52,  'Male',   '2022-03-05', 'Normal',        'Normal',        'Overweight',    'obese',   19.0, 105.0, 'Pending'),
('Althea Ong',           'Brgy. Navotas',     'Purok 4', 'George Ong',           55,  'Female', '2022-01-08', 'Normal',        'Normal',        'Normal',        'normal',  17.0, 108.0, 'Checked Up'),
('Dominic Cheng',        'Brgy. Navotas',     'Purok 1', 'Teresa Cheng',         57,  'Male',   '2022-01-02', 'Overweight',    'Normal',        'Obese',         'obese',   22.0, 110.0, 'Pending'),
('Frances Lee',          'Brgy. Navotas',     'Purok 2', 'Antonio Lee',          59,  'Female', '2021-08-15', 'Normal',        'Normal',        'Normal',        'normal',  18.0, 112.0, 'Pending'),
('Zach Arellano',        'Brgy. Navotas',     'Purok 3', 'Boy Arellano',         60,  'Male',   '2021-07-01', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up'),

-- Brgy. Palikpikan (15)
('Hannah Flores',        'Brgy. Palikpikan',  'Purok 1', 'Jun Flores',            2,  'Female', '2026-05-15', 'Normal',        'Normal',        'Normal',        'normal',   4.0,  51.0, 'Pending'),
('Aaron Velasco',        'Brgy. Palikpikan',  'Purok 2', 'Rosalinda Velasco',     6,  'Male',   '2026-01-20', 'Normal',        'Normal',        'Normal',        'normal',   6.5,  62.0, 'Pending'),
('Sara Domingo',         'Brgy. Palikpikan',  'Purok 3', 'Leonardo Domingo',     11,  'Female', '2025-08-05', 'Normal',        'Normal',        'Normal',        'normal',   8.5,  70.0, 'Pending'),
('Miguel Hernandez',     'Brgy. Palikpikan',  'Purok 4', 'Patricia Hernandez',   16,  'Male',   '2025-03-15', 'Underweight',   'Normal',        'Normal',        'normal',   9.0,  75.0, 'Pending'),
('Cheska Panganiban',    'Brgy. Palikpikan',  'Purok 1', 'Reynaldo Panganiban',  21,  'Female', '2024-10-08', 'Normal',        'Stunted',       'Normal',        'stunted',  9.8,  78.5, 'Pending'),
('Benedict Sy',          'Brgy. Palikpikan',  'Purok 2', 'Helen Sy',             26,  'Male',   '2024-05-20', 'Normal',        'Normal',        'Normal',        'normal',  11.2,  85.0, 'Pending'),
('Althea Ong',           'Brgy. Palikpikan',  'Purok 3', 'George Ong',           31,  'Female', '2024-01-10', 'Normal',        'Normal',        'Normal',        'normal',  12.0,  89.0, 'Checked Up'),
('Dominic Cheng',        'Brgy. Palikpikan',  'Purok 4', 'Teresa Cheng',         36,  'Male',   '2023-07-15', 'Normal',        'Normal',        'Normal',        'normal',  13.0,  93.0, 'Pending'),
('Frances Lee',          'Brgy. Palikpikan',  'Purok 1', 'Antonio Lee',          41,  'Female', '2023-02-20', 'Normal',        'Normal',        'Normal',        'normal',  14.0,  97.0, 'Pending'),
('Zach Arellano',        'Brgy. Palikpikan',  'Purok 2', 'Boy Arellano',         46,  'Male',   '2022-09-05', 'Severe Underweight', 'Severe Stunted', 'Severely Wasted', 'stunted', 12.0,  87.0, 'Pending'),
('Gela Magsaysay',       'Brgy. Palikpikan',  'Purok 3', 'Nena Magsaysay',       51,  'Female', '2022-04-18', 'Normal',        'Normal',        'Normal',        'normal',  16.0, 104.0, 'Pending'),
('TJ Rosales',           'Brgy. Palikpikan',  'Purok 4', 'Cesar Rosales',        54,  'Male',   '2022-01-10', 'Overweight',    'Normal',        'Overweight',    'obese',   20.0, 108.0, 'Checked Up'),
('Princess Dizon',       'Brgy. Palikpikan',  'Purok 1', 'Armando Dizon',        56,  'Female', '2022-01-05', 'Normal',        'Normal',        'Normal',        'normal',  17.5, 109.0, 'Pending'),
('Nathan Belen',         'Brgy. Palikpikan',  'Purok 2', 'Salome Belen',         58,  'Male',   '2022-01-08', 'Normal',        'Stunted',       'Normal',        'stunted', 15.5, 103.0, 'Pending'),
('Brianna Salcedo',      'Brgy. Palikpikan',  'Purok 3', 'Allan Salcedo',        60,  'Female', '2021-07-15', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up'),

-- Brgy. Sampaga (15)
('Ice Mercado',          'Brgy. Sampaga',     'Purok 1', 'Dante Mercado',         1,  'Female', '2026-06-20', 'Normal',        'Normal',        'Normal',        'normal',   3.5,  49.0, 'Pending'),
('Vince Herrera',        'Brgy. Sampaga',     'Purok 2', 'Carmen Herrera',        5,  'Male',   '2026-02-10', 'Normal',        'Normal',        'Normal',        'normal',   6.2,  61.0, 'Pending'),
('Patricia Luna',        'Brgy. Sampaga',     'Purok 3', 'Gregorio Luna',        10,  'Female', '2025-09-15', 'Normal',        'Normal',        'Normal',        'normal',   8.0,  69.0, 'Pending'),
('JM Tadeo',             'Brgy. Sampaga',     'Purok 4', 'Mercedes Tadeo',       15,  'Male',   '2025-04-08', 'Underweight',   'Normal',        'Normal',        'normal',   9.0,  74.0, 'Pending'),
('Bea Francisco',        'Brgy. Sampaga',     'Purok 1', 'Luis Francisco',       20,  'Female', '2024-11-20', 'Normal',        'Stunted',       'Normal',        'stunted',  9.8,  78.5, 'Pending'),
('Daryl Corpuz',         'Brgy. Sampaga',     'Purok 2', 'Benny Corpuz',         25,  'Male',   '2024-06-05', 'Normal',        'Normal',        'Normal',        'normal',  11.0,  84.0, 'Pending'),
('Ysabel Castro',        'Brgy. Sampaga',     'Purok 3', 'Rosario Castro',       30,  'Female', '2024-01-10', 'Normal',        'Normal',        'Normal',        'normal',  11.8,  88.0, 'Checked Up'),
('Rafael Gutierrez',     'Brgy. Sampaga',     'Purok 4', 'Felicidad Gutierrez',  35,  'Male',   '2023-08-15', 'Normal',        'Normal',        'Normal',        'normal',  12.8,  92.0, 'Pending'),
('Jasmine de Leon',      'Brgy. Sampaga',     'Purok 1', 'Samuel de Leon',       40,  'Female', '2023-03-01', 'Normal',        'Normal',        'Normal',        'normal',  13.5,  95.0, 'Pending'),
('Patrick Vargas',       'Brgy. Sampaga',     'Purok 2', 'Lourdes Vargas',       45,  'Male',   '2022-10-20', 'Severe Underweight', 'Stunted', 'Severely Wasted', 'stunted', 12.0,  88.0, 'Pending'),
('Kyla Animas',          'Brgy. Sampaga',     'Purok 3', 'Rolly Animas',         50,  'Female', '2022-05-10', 'Normal',        'Normal',        'Normal',        'normal',  16.0, 104.0, 'Pending'),
('Benedict Sy',          'Brgy. Sampaga',     'Purok 4', 'Helen Sy',             53,  'Male',   '2022-02-08', 'Overweight',    'Normal',        'Overweight',    'obese',   19.5, 107.0, 'Checked Up'),
('Althea Ong',           'Brgy. Sampaga',     'Purok 1', 'George Ong',           55,  'Female', '2022-01-10', 'Normal',        'Normal',        'Normal',        'normal',  17.0, 108.0, 'Pending'),
('Dominic Cheng',        'Brgy. Sampaga',     'Purok 2', 'Teresa Cheng',         57,  'Male',   '2022-01-05', 'Normal',        'Stunted',       'Normal',        'stunted', 15.0, 101.0, 'Pending'),
('Frances Lee',          'Brgy. Sampaga',     'Purok 3', 'Antonio Lee',          60,  'Female', '2021-07-15', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up'),

-- Brgy. Santol (15)
('Daryl Corpuz',         'Brgy. Santol',      'Purok 1', 'Benny Corpuz',          2,  'Male',   '2026-05-05', 'Normal',        'Normal',        'Normal',        'normal',   4.5,  52.0, 'Pending'),
('Ysabel Castro',        'Brgy. Santol',      'Purok 2', 'Rosario Castro',        7,  'Female', '2025-12-10', 'Normal',        'Normal',        'Normal',        'normal',   7.2,  64.0, 'Pending'),
('Rafael Gutierrez',     'Brgy. Santol',      'Purok 3', 'Felicidad Gutierrez',  13,  'Male',   '2025-06-20', 'Normal',        'Normal',        'Normal',        'normal',   9.0,  73.0, 'Pending'),
('Jasmine de Leon',      'Brgy. Santol',      'Purok 4', 'Samuel de Leon',       18,  'Female', '2025-01-05', 'Underweight',   'Normal',        'Normal',        'normal',   9.5,  77.0, 'Pending'),
('Patrick Vargas',       'Brgy. Santol',      'Purok 1', 'Lourdes Vargas',       23,  'Male',   '2024-08-15', 'Normal',        'Stunted',       'Normal',        'stunted', 10.0,  80.0, 'Pending'),
('Kyla Animas',          'Brgy. Santol',      'Purok 2', 'Rolly Animas',         28,  'Female', '2024-03-10', 'Normal',        'Normal',        'Normal',        'normal',  11.5,  86.0, 'Pending'),
('Benedict Sy',          'Brgy. Santol',      'Purok 3', 'Helen Sy',             33,  'Male',   '2023-10-20', 'Normal',        'Normal',        'Normal',        'normal',  12.5,  90.0, 'Checked Up'),
('Althea Ong',           'Brgy. Santol',      'Purok 4', 'George Ong',           38,  'Female', '2023-05-05', 'Normal',        'Normal',        'Normal',        'normal',  13.2,  93.0, 'Pending'),
('Dominic Cheng',        'Brgy. Santol',      'Purok 1', 'Teresa Cheng',         43,  'Male',   '2022-12-15', 'Severe Underweight', 'Severe Stunted', 'Severely Wasted', 'stunted', 11.5,  87.0, 'Pending'),
('Frances Lee',          'Brgy. Santol',      'Purok 2', 'Antonio Lee',          48,  'Female', '2022-07-01', 'Normal',        'Normal',        'Normal',        'normal',  15.5, 102.0, 'Pending'),
('Zach Arellano',        'Brgy. Santol',      'Purok 3', 'Boy Arellano',         52,  'Male',   '2022-03-20', 'Overweight',    'Normal',        'Overweight',    'obese',   19.5, 106.0, 'Pending'),
('Gela Magsaysay',       'Brgy. Santol',      'Purok 4', 'Nena Magsaysay',       55,  'Female', '2022-01-08', 'Normal',        'Normal',        'Normal',        'normal',  17.0, 108.0, 'Checked Up'),
('TJ Rosales',           'Brgy. Santol',      'Purok 1', 'Cesar Rosales',        57,  'Male',   '2022-01-02', 'Normal',        'Stunted',       'Normal',        'stunted', 15.0, 100.0, 'Pending'),
('Princess Dizon',       'Brgy. Santol',      'Purok 2', 'Armando Dizon',        59,  'Female', '2021-08-10', 'Normal',        'Normal',        'Normal',        'normal',  18.5, 113.0, 'Pending'),
('Nathan Belen',         'Brgy. Santol',      'Purok 3', 'Salome Belen',         60,  'Male',   '2021-07-01', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up'),

-- Brgy. Dilao (15)
('Kyla Animas',          'Brgy. Dilao',       'Purok 1', 'Rolly Animas',          1,  'Female', '2026-06-20', 'Normal',        'Normal',        'Normal',        'normal',   3.8,  50.0, 'Pending'),
('Benedict Sy',          'Brgy. Dilao',       'Purok 2', 'Helen Sy',              5,  'Male',   '2026-02-15', 'Normal',        'Normal',        'Normal',        'normal',   6.0,  60.0, 'Pending'),
('Althea Ong',           'Brgy. Dilao',       'Purok 3', 'George Ong',           10,  'Female', '2025-09-01', 'Normal',        'Normal',        'Normal',        'normal',   8.0,  69.0, 'Pending'),
('Dominic Cheng',        'Brgy. Dilao',       'Purok 4', 'Teresa Cheng',         15,  'Male',   '2025-04-20', 'Underweight',   'Normal',        'Normal',        'normal',   9.0,  74.0, 'Pending'),
('Frances Lee',          'Brgy. Dilao',       'Purok 1', 'Antonio Lee',          20,  'Female', '2024-11-10', 'Normal',        'Stunted',       'Normal',        'stunted',  9.8,  78.5, 'Pending'),
('Zach Arellano',        'Brgy. Dilao',       'Purok 2', 'Boy Arellano',         25,  'Male',   '2024-06-05', 'Normal',        'Normal',        'Normal',        'normal',  11.0,  84.0, 'Pending'),
('Gela Magsaysay',       'Brgy. Dilao',       'Purok 3', 'Nena Magsaysay',       30,  'Female', '2024-01-15', 'Normal',        'Normal',        'Normal',        'normal',  11.8,  88.0, 'Checked Up'),
('TJ Rosales',           'Brgy. Dilao',       'Purok 4', 'Cesar Rosales',        35,  'Male',   '2023-08-08', 'Normal',        'Normal',        'Normal',        'normal',  12.8,  92.0, 'Pending'),
('Princess Dizon',       'Brgy. Dilao',       'Purok 1', 'Armando Dizon',        40,  'Female', '2023-03-20', 'Normal',        'Normal',        'Normal',        'normal',  13.5,  95.0, 'Pending'),
('Nathan Belen',         'Brgy. Dilao',       'Purok 2', 'Salome Belen',         45,  'Male',   '2022-10-10', 'Severe Underweight', 'Stunted', 'Severely Wasted', 'stunted', 12.0,  88.0, 'Pending'),
('Brianna Salcedo',      'Brgy. Dilao',       'Purok 3', 'Allan Salcedo',        50,  'Female', '2022-05-15', 'Normal',        'Normal',        'Normal',        'normal',  16.0, 104.0, 'Pending'),
('Iñigo Magtibay',       'Brgy. Dilao',       'Purok 4', 'Susan Magtibay',       53,  'Male',   '2022-02-08', 'Overweight',    'Normal',        'Overweight',    'obese',   19.5, 107.0, 'Checked Up'),
('Rina Concepcion',      'Brgy. Dilao',       'Purok 1', 'Ramon Concepcion',     55,  'Female', '2022-01-10', 'Normal',        'Normal',        'Normal',        'normal',  17.0, 108.0, 'Pending'),
('Diego Alejo',          'Brgy. Dilao',       'Purok 2', 'Lina Alejo',           57,  'Male',   '2022-01-05', 'Normal',        'Stunted',       'Normal',        'stunted', 15.0, 101.0, 'Pending'),
('Czarina Bello',        'Brgy. Dilao',       'Purok 3', 'Fidel Bello',          60,  'Female', '2021-07-15', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up'),

-- Brgy. Dalig (15)
('Zach Arellano',        'Brgy. Dalig',       'Purok 1', 'Boy Arellano',          3,  'Male',   '2026-04-08', 'Normal',        'Normal',        'Normal',        'normal',   5.0,  55.0, 'Pending'),
('Gela Magsaysay',       'Brgy. Dalig',       'Purok 2', 'Nena Magsaysay',        8,  'Female', '2025-11-05', 'Normal',        'Normal',        'Normal',        'normal',   7.5,  66.0, 'Pending'),
('TJ Rosales',           'Brgy. Dalig',       'Purok 3', 'Cesar Rosales',        14,  'Male',   '2025-05-15', 'Normal',        'Normal',        'Normal',        'normal',   9.2,  74.0, 'Pending'),
('Princess Dizon',       'Brgy. Dalig',       'Purok 4', 'Armando Dizon',        19,  'Female', '2024-12-01', 'Underweight',   'Normal',        'Normal',        'normal',   9.5,  77.0, 'Pending'),
('Nathan Belen',         'Brgy. Dalig',       'Purok 1', 'Salome Belen',         24,  'Male',   '2024-07-20', 'Normal',        'Stunted',       'Normal',        'stunted', 10.2,  80.0, 'Pending'),
('Brianna Salcedo',      'Brgy. Dalig',       'Purok 2', 'Allan Salcedo',        29,  'Female', '2024-02-10', 'Normal',        'Normal',        'Normal',        'normal',  11.5,  86.0, 'Pending'),
('Iñigo Magtibay',       'Brgy. Dalig',       'Purok 3', 'Susan Magtibay',       34,  'Male',   '2023-09-15', 'Normal',        'Normal',        'Normal',        'normal',  12.5,  90.0, 'Checked Up'),
('Rina Concepcion',      'Brgy. Dalig',       'Purok 4', 'Ramon Concepcion',     39,  'Female', '2023-04-08', 'Normal',        'Normal',        'Normal',        'normal',  13.2,  93.0, 'Pending'),
('Diego Alejo',          'Brgy. Dalig',       'Purok 1', 'Lina Alejo',           44,  'Male',   '2022-11-20', 'Severe Underweight', 'Severe Stunted', 'Severely Wasted', 'stunted', 11.5,  87.0, 'Pending'),
('Czarina Bello',        'Brgy. Dalig',       'Purok 2', 'Fidel Bello',          49,  'Female', '2022-06-05', 'Normal',        'Normal',        'Normal',        'normal',  15.5, 102.0, 'Pending'),
('Enzo Marcelo',         'Brgy. Dalig',       'Purok 3', 'Jun Marcelo',          53,  'Male',   '2022-02-18', 'Overweight',    'Normal',        'Overweight',    'obese',   19.5, 106.0, 'Pending'),
('Mika Sevilla',         'Brgy. Dalig',       'Purok 4', 'Merle Sevilla',        55,  'Female', '2022-01-10', 'Normal',        'Normal',        'Normal',        'normal',  17.0, 108.0, 'Checked Up'),
('Ace Villarosa',        'Brgy. Dalig',       'Purok 1', 'Elena Villarosa',      57,  'Male',   '2022-01-05', 'Normal',        'Stunted',       'Normal',        'stunted', 15.0, 100.0, 'Pending'),
('Stella Magno',         'Brgy. Dalig',       'Purok 2', 'Virgilio Magno',       59,  'Female', '2021-08-10', 'Normal',        'Normal',        'Normal',        'normal',  18.5, 113.0, 'Pending'),
('Harold Natividad',     'Brgy. Dalig',       'Purok 3', 'Lourdes Natividad',    60,  'Male',   '2021-07-01', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up'),

-- Brgy. Langgangan (15)
('Brianna Salcedo',      'Brgy. Langgangan',  'Purok 1', 'Allan Salcedo',         1,  'Female', '2026-06-25', 'Normal',        'Normal',        'Normal',        'normal',   3.5,  49.0, 'Pending'),
('Iñigo Magtibay',       'Brgy. Langgangan',  'Purok 2', 'Susan Magtibay',        4,  'Male',   '2026-03-12', 'Normal',        'Normal',        'Normal',        'normal',   5.8,  58.0, 'Pending'),
('Rina Concepcion',      'Brgy. Langgangan',  'Purok 3', 'Ramon Concepcion',      9,  'Female', '2025-10-08', 'Normal',        'Normal',        'Normal',        'normal',   7.8,  68.0, 'Pending'),
('Diego Alejo',          'Brgy. Langgangan',  'Purok 4', 'Lina Alejo',           14,  'Male',   '2025-05-20', 'Underweight',   'Normal',        'Normal',        'normal',   9.0,  74.0, 'Pending'),
('Czarina Bello',        'Brgy. Langgangan',  'Purok 1', 'Fidel Bello',          19,  'Female', '2024-12-10', 'Normal',        'Stunted',       'Normal',        'stunted',  9.5,  77.0, 'Pending'),
('Enzo Marcelo',         'Brgy. Langgangan',  'Purok 2', 'Jun Marcelo',          24,  'Male',   '2024-07-15', 'Normal',        'Normal',        'Normal',        'normal',  11.0,  84.0, 'Pending'),
('Mika Sevilla',         'Brgy. Langgangan',  'Purok 3', 'Merle Sevilla',        29,  'Female', '2024-02-05', 'Normal',        'Normal',        'Normal',        'normal',  11.5,  86.0, 'Checked Up'),
('Ace Villarosa',        'Brgy. Langgangan',  'Purok 4', 'Elena Villarosa',      34,  'Male',   '2023-09-18', 'Normal',        'Normal',        'Normal',        'normal',  12.5,  90.0, 'Pending'),
('Stella Magno',         'Brgy. Langgangan',  'Purok 1', 'Virgilio Magno',       39,  'Female', '2023-04-10', 'Normal',        'Normal',        'Normal',        'normal',  13.5,  94.0, 'Pending'),
('Harold Natividad',     'Brgy. Langgangan',  'Purok 2', 'Lourdes Natividad',    44,  'Male',   '2022-11-20', 'Severe Underweight', 'Stunted', 'Severely Wasted', 'stunted', 12.0,  88.0, 'Pending'),
('Ice Mercado',          'Brgy. Langgangan',  'Purok 3', 'Dante Mercado',        49,  'Female', '2022-06-05', 'Normal',        'Normal',        'Normal',        'normal',  15.5, 102.0, 'Pending'),
('Vince Herrera',        'Brgy. Langgangan',  'Purok 4', 'Carmen Herrera',       53,  'Male',   '2022-02-18', 'Overweight',    'Normal',        'Overweight',    'obese',   20.0, 106.0, 'Checked Up'),
('Patricia Luna',        'Brgy. Langgangan',  'Purok 1', 'Gregorio Luna',        55,  'Female', '2022-01-10', 'Normal',        'Normal',        'Normal',        'normal',  17.0, 108.0, 'Pending'),
('JM Tadeo',             'Brgy. Langgangan',  'Purok 2', 'Mercedes Tadeo',       57,  'Male',   '2022-01-05', 'Normal',        'Stunted',       'Normal',        'stunted', 15.0, 101.0, 'Pending'),
('Bea Francisco',        'Brgy. Langgangan',  'Purok 3', 'Luis Francisco',       60,  'Female', '2021-07-15', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up'),

-- Brgy. Canda (15)
('Enzo Marcelo',         'Brgy. Canda',       'Purok 1', 'Jun Marcelo',           2,  'Male',   '2026-05-10', 'Normal',        'Normal',        'Normal',        'normal',   4.2,  51.0, 'Pending'),
('Mika Sevilla',         'Brgy. Canda',       'Purok 2', 'Merle Sevilla',         7,  'Female', '2025-12-08', 'Normal',        'Normal',        'Normal',        'normal',   7.0,  64.0, 'Pending'),
('Ace Villarosa',        'Brgy. Canda',       'Purok 3', 'Elena Villarosa',      12,  'Male',   '2025-07-15', 'Normal',        'Normal',        'Normal',        'normal',   8.8,  72.0, 'Pending'),
('Stella Magno',         'Brgy. Canda',       'Purok 4', 'Virgilio Magno',       17,  'Female', '2025-02-01', 'Underweight',   'Normal',        'Normal',        'normal',   9.0,  75.0, 'Pending'),
('Harold Natividad',     'Brgy. Canda',       'Purok 1', 'Lourdes Natividad',    22,  'Male',   '2024-09-20', 'Normal',        'Stunted',       'Normal',        'stunted',  9.8,  78.5, 'Pending'),
('Ice Mercado',          'Brgy. Canda',       'Purok 2', 'Dante Mercado',        27,  'Female', '2024-04-08', 'Normal',        'Normal',        'Normal',        'normal',  11.2,  85.0, 'Pending'),
('Vince Herrera',        'Brgy. Canda',       'Purok 3', 'Carmen Herrera',       32,  'Male',   '2023-11-15', 'Normal',        'Normal',        'Normal',        'normal',  12.0,  89.0, 'Checked Up'),
('Patricia Luna',        'Brgy. Canda',       'Purok 4', 'Gregorio Luna',        37,  'Female', '2023-06-01', 'Normal',        'Normal',        'Normal',        'normal',  13.0,  93.0, 'Pending'),
('JM Tadeo',             'Brgy. Canda',       'Purok 1', 'Mercedes Tadeo',       42,  'Male',   '2023-01-20', 'Normal',        'Normal',        'Normal',        'normal',  14.0,  97.0, 'Pending'),
('Bea Francisco',        'Brgy. Canda',       'Purok 2', 'Luis Francisco',       47,  'Female', '2022-08-10', 'Severe Underweight', 'Stunted', 'Severely Wasted', 'stunted', 12.0,  87.0, 'Pending'),
('Daryl Corpuz',         'Brgy. Canda',       'Purok 3', 'Benny Corpuz',         52,  'Male',   '2022-03-05', 'Normal',        'Normal',        'Overweight',    'obese',   19.0, 105.0, 'Pending'),
('Ysabel Castro',        'Brgy. Canda',       'Purok 4', 'Rosario Castro',       55,  'Female', '2022-01-08', 'Normal',        'Normal',        'Normal',        'normal',  17.0, 108.0, 'Checked Up'),
('Rafael Gutierrez',     'Brgy. Canda',       'Purok 1', 'Felicidad Gutierrez',  57,  'Male',   '2022-01-02', 'Overweight',    'Normal',        'Obese',         'obese',   22.0, 110.0, 'Pending'),
('Jasmine de Leon',      'Brgy. Canda',       'Purok 2', 'Samuel de Leon',       59,  'Female', '2021-08-15', 'Normal',        'Normal',        'Normal',        'normal',  18.5, 113.0, 'Pending'),
('Patrick Vargas',       'Brgy. Canda',       'Purok 3', 'Lourdes Vargas',       60,  'Male',   '2021-07-01', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up'),

-- Brgy. Pooc (15)
('Niana Tolentino',      'Brgy. Pooc',        'Purok 1', 'Oscar Tolentino',       3,  'Female', '2026-04-20', 'Normal',        'Normal',        'Normal',        'normal',   5.2,  55.0, 'Pending'),
('Xavier Ranara',        'Brgy. Pooc',        'Purok 2', 'Gina Ranara',           8,  'Male',   '2025-11-10', 'Normal',        'Normal',        'Normal',        'normal',   7.5,  66.0, 'Pending'),
('Angelique Tuazon',     'Brgy. Pooc',        'Purok 3', 'Jun Tuazon',           13,  'Female', '2025-06-05', 'Normal',        'Normal',        'Normal',        'normal',   9.0,  73.0, 'Pending'),
('Raphael Mendoza',      'Brgy. Pooc',        'Purok 4', 'Sonia Mendoza',        18,  'Male',   '2025-01-15', 'Underweight',   'Normal',        'Normal',        'normal',   9.5,  77.0, 'Pending'),
('Bianca Suarez',        'Brgy. Pooc',        'Purok 1', 'Rogelio Suarez',       23,  'Female', '2024-08-08', 'Normal',        'Stunted',       'Normal',        'stunted', 10.0,  80.0, 'Pending'),
('Jerome Villanueva',    'Brgy. Pooc',        'Purok 2', 'Corazon Villanueva',   28,  'Male',   '2024-03-20', 'Normal',        'Normal',        'Normal',        'normal',  11.5,  86.0, 'Pending'),
('Camille Ramos',        'Brgy. Pooc',        'Purok 3', 'Dante Ramos',          33,  'Female', '2023-10-10', 'Normal',        'Normal',        'Normal',        'normal',  12.5,  90.0, 'Checked Up'),
('Luis Magsaysay',       'Brgy. Pooc',        'Purok 4', 'Nora Magsaysay',       38,  'Male',   '2023-05-15', 'Normal',        'Normal',        'Normal',        'normal',  13.2,  93.0, 'Pending'),
('Darlene Aquino',       'Brgy. Pooc',        'Purok 1', 'Efren Aquino',         43,  'Female', '2022-12-20', 'Severe Underweight', 'Severe Stunted', 'Severely Wasted', 'stunted', 11.5,  87.0, 'Pending'),
('Marco Pascua',         'Brgy. Pooc',        'Purok 2', 'Gloria Pascua',        48,  'Male',   '2022-07-05', 'Normal',        'Normal',        'Normal',        'normal',  15.5, 102.0, 'Pending'),
('Trina Dela Peña',      'Brgy. Pooc',        'Purok 3', 'Ramon Dela Peña',      52,  'Female', '2022-03-18', 'Overweight',    'Normal',        'Overweight',    'obese',   19.5, 106.0, 'Pending'),
('Kyle Bautista',        'Brgy. Pooc',        'Purok 4', 'Lourdes Bautista',     55,  'Male',   '2022-01-10', 'Normal',        'Normal',        'Normal',        'normal',  17.0, 108.0, 'Checked Up'),
('Patrice Santos',       'Brgy. Pooc',        'Purok 1', 'Jun Santos',           57,  'Female', '2022-01-05', 'Normal',        'Stunted',       'Normal',        'stunted', 15.0, 100.0, 'Pending'),
('Bryan Gonzales',       'Brgy. Pooc',        'Purok 2', 'Teresa Gonzales',      59,  'Male',   '2021-08-10', 'Normal',        'Normal',        'Normal',        'normal',  18.5, 113.0, 'Pending'),
('Joy Navarro',          'Brgy. Pooc',        'Purok 3', 'Romeo Navarro',        60,  'Female', '2021-07-01', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up'),

-- Brgy. Tanggoy (15)
('Jerome Villanueva',    'Brgy. Tanggoy',     'Purok 1', 'Corazon Villanueva',    2,  'Male',   '2026-05-18', 'Normal',        'Normal',        'Normal',        'normal',   4.5,  52.0, 'Pending'),
('Camille Ramos',        'Brgy. Tanggoy',     'Purok 2', 'Dante Ramos',           7,  'Female', '2025-12-22', 'Normal',        'Normal',        'Normal',        'normal',   7.0,  64.0, 'Pending'),
('Luis Magsaysay',       'Brgy. Tanggoy',     'Purok 3', 'Nora Magsaysay',       12,  'Male',   '2025-07-10', 'Normal',        'Normal',        'Normal',        'normal',   8.8,  72.0, 'Pending'),
('Darlene Aquino',       'Brgy. Tanggoy',     'Purok 4', 'Efren Aquino',         17,  'Female', '2025-02-05', 'Underweight',   'Normal',        'Normal',        'normal',   9.0,  75.0, 'Pending'),
('Marco Pascua',         'Brgy. Tanggoy',     'Purok 1', 'Gloria Pascua',        22,  'Male',   '2024-09-15', 'Normal',        'Stunted',       'Normal',        'stunted',  9.8,  78.5, 'Pending'),
('Trina Dela Peña',      'Brgy. Tanggoy',     'Purok 2', 'Ramon Dela Peña',      27,  'Female', '2024-04-08', 'Normal',        'Normal',        'Normal',        'normal',  11.2,  85.0, 'Pending'),
('Kyle Bautista',        'Brgy. Tanggoy',     'Purok 3', 'Lourdes Bautista',     32,  'Male',   '2023-11-20', 'Normal',        'Normal',        'Normal',        'normal',  12.0,  89.0, 'Checked Up'),
('Patrice Santos',       'Brgy. Tanggoy',     'Purok 4', 'Jun Santos',           37,  'Female', '2023-06-05', 'Normal',        'Normal',        'Normal',        'normal',  13.0,  93.0, 'Pending'),
('Bryan Gonzales',       'Brgy. Tanggoy',     'Purok 1', 'Teresa Gonzales',      42,  'Male',   '2023-01-15', 'Normal',        'Normal',        'Normal',        'normal',  14.0,  97.0, 'Pending'),
('Joy Navarro',          'Brgy. Tanggoy',     'Purok 2', 'Romeo Navarro',        47,  'Female', '2022-08-08', 'Severe Underweight', 'Stunted', 'Severely Wasted', 'stunted', 12.0,  87.0, 'Pending'),
('Carlo Fernandez',      'Brgy. Tanggoy',     'Purok 3', 'Gemma Fernandez',      52,  'Male',   '2022-03-20', 'Overweight',    'Normal',        'Overweight',    'obese',   19.0, 105.0, 'Pending'),
('Rica Flores',          'Brgy. Tanggoy',     'Purok 4', 'Jun Flores',           55,  'Female', '2022-01-08', 'Normal',        'Normal',        'Normal',        'normal',  17.0, 108.0, 'Checked Up'),
('Migs Salvador',        'Brgy. Tanggoy',     'Purok 1', 'Lina Salvador',        57,  'Male',   '2022-01-02', 'Normal',        'Stunted',       'Normal',        'stunted', 15.0, 100.0, 'Pending'),
('Arianne De Leon',      'Brgy. Tanggoy',     'Purok 2', 'Samuel De Leon',       59,  'Female', '2021-08-15', 'Normal',        'Normal',        'Normal',        'normal',  18.5, 113.0, 'Pending'),
('Kyle Medina',          'Brgy. Tanggoy',     'Purok 3', 'Nora Medina',          60,  'Male',   '2021-07-01', 'Normal',        'Normal',        'Normal',        'normal',  19.0, 115.0, 'Checked Up');
